'use strict';

const ACTIONS = {
    CREATE_VOTE: 'ACTION_CREATE_VOTE',
    CREATE_HEADER: 'ACTION_CREATE_HEADER',
    CREATE_TEXT: 'ACTION_CREATE_TEXT',
    CREATE_OPTION: 'ACTION_CREATE_OPTION',
    CAST_VOTE: 'ACTION_CAST_VOTE',
    HEARS_CANCEL: 'ACTION_HEARS_CANCEL',
    HEARS_DONE: 'ACTION_HEARS_DONE',
    HEARS_RESULTS: 'ACTION_HEARS_RESULTS',
};

module.exports = { ACTIONS };
