'use strict';

const ACTION_HEARS_CANCEL = 'ACTION_HEARS_CANCEL';
const ACTION_HEARS_DONE = 'ACTION_HEARS_DONE';
const ACTION_HEARS_RESULTS = 'ACTION_HEARS_RESULTS';

module.exports = { ACTION_HEARS_CANCEL, ACTION_HEARS_DONE, ACTION_HEARS_RESULTS };
