'use strict';

const STATES = {
  DEFAULT: 'STATE_DEFAULT',
  CREATE_HEADER: 'STATE_CREATE_HEADER',
  CREATE_TEXT: 'STATE_CREATE_TEXT',
  CREATE_OPTION: 'STATE_CREATE_OPTION',
  ANSWER: 'STATE_ANSWER',
}

module.exports = { STATES };
