'use strict';

const STATE_DEFAULT = 'STATE_DEFAULT';
const STATE_CREATE_HEADER = 'STATE_CREATE_HEADER';
const STATE_CREATE_TEXT = 'STATE_CREATE_TEXT';
const STATE_CREATE_OPTION = 'STATE_CREATE_OPTION';
const STATE_ANSWER = 'STATE_ANSWER';

module.exports = {
  STATE_DEFAULT,
  STATE_CREATE_HEADER,
  STATE_CREATE_TEXT,
  STATE_CREATE_OPTION,
  STATE_ANSWER
};
